# Travis CI Configuration file
# @link https://travis-ci.org/

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# PHP
# @link http://docs.travis-ci.com/user/languages/php/
language: php

# Declare versions of PHP to test
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

# Declare versions of Wordpress to test
env:
  - WP_VERSION=4.1
  - WP_VERSION=4.0
  - WP_VERSION=3.9

# before_install: Failures in this section will result in build status 'errored'
before_install:
  # update composer
  - composer self-update

  # setup WP
  - export PLUGIN=rutube
  - export WP_INSTALL_DIR=/tmp/wordpress
  - export WP_DIR=$WP_INSTALL_DIR/src
  - export WP_PLUGIN_DIR=$WP_DIR/wp-content/plugins/$PLUGIN
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_INSTALL_DIR
  - ls -al $WP_INSTALL_DIR
  - ls -al $WP_DIR

  # setup config
  - cp $WP_INSTALL_DIR/wp-tests-config-sample.php $WP_INSTALL_DIR/wp-tests-config.php
  - sed -i -- 's/youremptytestdbnamehere/wordpress/g' $WP_INSTALL_DIR/wp-tests-config.php
  - sed -i -- 's/yourusernamehere/root/g' $WP_INSTALL_DIR/wp-tests-config.php
  - sed -i -- 's/yourpasswordhere//g' $WP_INSTALL_DIR/wp-tests-config.php

  # create database
  - mysql -e 'CREATE DATABASE wordpress;' -uroot

  # copy plugin to WP
  - mkdir -p $WP_PLUGIN_DIR
  - cp -R * $WP_PLUGIN_DIR
  - cd $WP_PLUGIN_DIR

install:
  - composer install

script: phpunit
