# Travis CI Configuration file
# @link https://travis-ci.org/

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# PHP
# @link http://docs.travis-ci.com/user/languages/php/
language: php

# Declare versions of PHP to test
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

# Declare versions of Wordpress to test
env:
  - WP_VERSION=4.1
  - WP_VERSION=4.0
  - WP_VERSION=3.9

# before_install: Failures in this section will result in build status 'errored'
before_install:
  # update composer
  - composer self-update

  # setup WP
  - PLUGIN=rutube-wordpress
  - WP_INSTALL_DIR=/tmp
  - WP_DIR=$WP_INSTALL_DIR/wordpress
  - WP_PLUGINS_DIR=$WP_DIR/wp-content/plugins
  - composer require johnpbloch/wordpress:$WP_VERSION -d $WP_INSTALL_DIR
  - mkdir -p $WP_PLUGINS_DIR/$PLUGIN

  # copy plugin to WP
  - cp -R * $WP_PLUGINS_DIR/$PLUGIN
  - cd $WP_PLUGINS_DIR/$PLUGIN

  # setup config
  - cp $WP_DIR/wp-config-sample.php $WP_DIR/wp-config.php
  - sed -i -- 's/database_name_here/wordpress/g' $WP_DIR/wp-config.php
  - sed -i -- 's/username_here/root/g' $WP_DIR/wp-config.php
  - sed -i -- 's/password_here//g' $WP_DIR/wp-config.php

  # create database
  - mysql -e 'CREATE DATABASE wordpress;' -uroot

install:
  - composer install

script: phpunit
